test2

diff --git a/.github/workflows/daily-security.yml b/.github/workflows/daily-security.yml
--- a/.github/workflows/daily-security.yml
+++ b/.github/workflows/daily-security.yml
@@ -2,12 +2,12 @@ name: Daily Security Pipeline
 
 on:
   schedule:
-    - cron: '0 1 * * *' 
-  workflow_dispatch:
+    - cron: '0 1 * * *'  # Tous les jours à 01h00 UTC
+  workflow_dispatch:      # Exécution manuelle possible
 
 permissions:
   contents: read
-  security-events: write  
+  security-events: write  # Nécessaire pour publier les rapports SARIF
 
 jobs:
   DependenciesAnalysis:
@@ -36,13 +36,13 @@ jobs:
 
       - name: Télécharger OSV-Scanner
         run: |
-          curl -sSfL https://github.com/google/osv-scanner/releases/download/v2.0.2/osv-scanner_darwin_amd64 -o osv-scanner
+          curl -sSfL https://github.com/google/osv-scanner/releases/download/v2.0.2/osv-scanner_linux_amd64 -o osv-scanner
           chmod +x osv-scanner
           sudo mv osv-scanner /usr/local/bin/
 
       - name: Lancer OSV-Scanner
         run: |
-          osv-scanner --lockfile=**/package-lock.json --format sarif --output osv-report.sarif || echo "OSV scan terminé"
+          osv-scanner --format sarif --output osv-report.sarif || echo "OSV scan terminé"
 
       - name: Envoyer le rapport SARIF
         uses: github/codeql-action/upload-sarif@v3
